### ISSUE TITLE
Help for missing data files in test folder

### ISSUE THREAD

**Issue by akashppatel** [fluffynukeit/jMatFile#3]
Hi, 
I am new to this world, Sorry if question is irrelevant
I fired npm install, get this as output:
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1

Now I have node_module, I fired npm test, but result says data file missing, e.g
test\data\scalar_primitives.mat
row_primitives.mat

I physically don't see these files in test\data\ folder, have i done something wrong?

Thank you.

**Comment by fluffynukeit** [comment]
You need to download octave, which is free, to generate the files. The repo
has a .m file that you run in octave that will create the data files needed
for test. They aren't saved in the repo.

**Comment by akashppatel** [comment]
Thankyou :)
